export const INCREMENT_REQ = 'INCREMENT_REQ'
export const INCREMENT_SUCCESS = 'INCREMENT_SUCCESS'
export const INCREMENT_FAIL = 'INCREMENT_FAIL'

export const DECREMENT_REQ = 'DECREMENT_REQ'
export const DECREMENT_SUCCESS = 'DECREMENT_SUCCESS'
export const DECREMENT_FAIL = 'DECREMENT_FAIL'